"""'Initial'

Revision ID: 65145c1cfbcb
Revises: 
Create Date: 2022-02-04 13:31:39.029364

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '65145c1cfbcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_db',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('register_data', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_db')
    # ### end Alembic commands ###
