"""Added required tables

Revision ID: 687dd701acf9
Revises: 
Create Date: 2022-02-03 11:57:56.067741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687dd701acf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
